shard.yml
src/helpers/versions.cr
src/resolvers/git.cr
src/script.cr
src/spec.cr
test/support/factories.cr

Compatibility with Crystal > 0.7.6

---

.travis.yml

TravisCI: OSX support

---

src/resolvers/git.cr
src/script.cr
test/support/cli.cr
test/support/factories.cr

Fixed needed for shards to compile in 0.9.0.
Once this is merged and there's a new release we can use that new release in the homebrew formula.
If you want, you can give me and @waj write access to this repository, maybe with instructions on how to release, so we can do these kind of changes on every release and free you from this task :-)
Thanks!

Updated to Crystal 0.9.0

---

src/resolvers/path.cr
test/integration/install_test.cr
test/integration/update_test.cr
test/integration_helper.cr
test/support/cli.cr
test/support/factories.cr

Fix: expand path in symlink for path dependency

---

SPEC.md
src/spec.cr
test/spec_test.cr

Add libraries field

---

SPEC.md
shard.yml
src/spec.cr
test/spec_test.cr

Add crystal:version entry

---

SPEC.md

Reused the explanation from http://bundler.io/v1.5/gemfile.html

Documented `~>` version specifier

---

src/logger.cr

Since crystal-lang/crystal#1781 is fixed, custom `Logger` class can be removed (as per comment in `src/logger.cr`).
ATM trying to `require` logger with shards fails with:
```
in /usr/local/Cellar/crystal-lang/0.20.5_2/src/logger.cr:42: can't reopen enum and add more constants to it
```

Remove custom Logger class

---

src/commands/prune.cr

`make` was failing for me. This fixes it.

Fixes broken file_utils import path

---

README.md

As per https://github.com/crystal-lang/crystal/pull/5544.

Remove references to `crystal deps`

---

SPEC.md

Please see [my comment] below(https://github.com/crystal-lang/shards/pull/119#issuecomment-261271199) for an up to date description.

Lift semver constraint; add calver recommendation

---

src/resolvers/git.cr
src/resolvers/path.cr
src/resolvers/resolver.cr
test/git_resolver_test.cr
test/integration/install_test.cr
test/integration_helper.cr
test/manager_test.cr
test/path_resolver_test.cr

Remove support for obsolete Projectfile

---

CHANGELOG.md

Add release dates to CHANGELOG

---

.circleci/config.yml

Fixup dry of steps

---

man/shards.1
src/cli.cr

Extend documentation in manpage and `--help` command

---

src/cli.cr
src/commands/check.cr
src/commands/command.cr
src/commands/init.cr
src/commands/list.cr
src/errors.cr
src/helpers/natural_sort.cr
src/helpers/versions.cr
src/lock.cr
src/logger.cr
src/manager.cr
src/resolvers/git.cr
src/spec.cr
src/version.cr
test/git_resolver_test.cr
test/integration/check_test.cr
test/integration/init_test.cr
test/integration/install_test.cr
test/integration/list_test.cr
test/integration/prune_test.cr
test/integration/update_test.cr
test/integration_helper.cr
test/lock_test.cr
test/manager_test.cr
test/resolver_test.cr
test/support/factories.cr
test/support/mock_resolver.cr
test/test_helper.cr

SSIA. These are mostly white-space changes.
There are couple of instances where I've left code unformatted, since formatter is mostly wrong in those (usually about indenting commented code).
This is the first of cleanup PRs I'd like to send.

Format codebase with `crystal tool format`

---

src/cli.cr
src/commands/list.cr
test/integration/list_test.cr

This should fix issue #218.
-----
On the other hand, it would be nice to have a more flexible options parser. It could make this code a lot cleaner too, and I'm sure some commands could be extended this way. What do you think?

Add --tree option to shards list

---

src/dependency.cr
src/package.cr

Path resolver: report 'version at path' when installing/using

---

src/cli.cr
src/config.cr
src/manager.cr
src/package.cr
src/resolvers/git.cr
src/resolvers/resolver.cr
test/integration/update_test.cr

--local command line argument

---

src/commands/check.cr
src/config.cr
src/resolvers/git.cr
src/solver.cr
src/solver/sat.cr
src/versions.cr

There are a few small formatting diffs that kept popping up during my other PR.

Format code (no functional change)

---

spec/integration/prune_spec.cr
src/commands/prune.cr

I forgot to update "prune" with #366

Remove entries from shards info file when pruning

---

spec/integration/install_spec.cr
spec/integration/spec_helper.cr
src/commands/install.cr
src/molinillo_solver.cr

Install dependencies in reverse topological order

---

Makefile

Signed-off-by: Anatol Pomozov <anatol.pomozov@gmail.com>

Allow Makefile envvars to be overwritten from a command line

---

src/requirement.cr

Fixes a recent new warning in 0.35

Fix Crystal 0.35 compatibility

---

spec/integration/install_spec.cr
spec/integration/spec_helper.cr
src/molinillo_solver.cr

Allow crystal: x.y values (without patch)

---

spec/unit/resolver_spec.cr
spec/unit/spec_spec.cr
src/errors.cr
src/resolvers/path.cr
src/resolvers/resolver.cr
src/spec.cr

Add shard context to ParseError

---

README.md

Hi!
This is a pull request to fix the broken link.
Best regards!

Fixed a broken link in the README.md

---

shard.lock
shard.yml

Update crystal for 1.x compatibility

Bump crystal-molinillo to 0.2.0

---

docs/shards.adoc

Follow-up to #422. Documents the override behaviour.

Add documentation for `shard.override.yml`

---

spec/integration/install_spec.cr
src/override.cr

Fix to allow empty shard.override.yml

---

README.md

Add Getting started section to README

---

spec/integration/install_spec.cr
spec/integration/spec_helper.cr
src/resolvers/git.cr

Fix error message for invalid shard.yml

---

README.md
man/shard.yml.5
man/shards.1
src/lock.cr
src/resolvers/git.cr

This pull request changes some misspelled words and fixes link to
license (_it was broken_).

Fix grammar problems

---

docs/shard.yml.adoc
man/shard.yml.5
spec/unit/versions_spec.cr

* Clarify the semantics of `~>` operator
* Took inspiration from https://getcomposer.org/doc/articles/versions.md#tilde-version-range- as they're semantically the same.
* Add a few additional test assertions to capture these uncommon cases
Resolves #570

Tilde version operator improvements

---

spec/integration/install_spec.cr
spec/integration/spec_helper.cr
src/package.cr

Fix install non-`.exe` executables on Windows

---

CHANGELOG.md

See https://github.com/crystal-lang/crystal/issues/13620

Adjust changelog format to follow that of crystal

---

Makefile
docs.mk

This goes on top of #609 to avoid merge conflicts.

Refactor Makefile phony declaration

---

Makefile

Adapted from crystal's Makefile: https://github.com/crystal-lang/crystal/blob/0da17469fe1d3ea0078585707db8809722813aec/Makefile#L186-L191

Add make recipe `install_dlls`
