- src/version.cr
I am unable to build shards on OSX due to `date --utc` being unavailable on OSX. Changed `date --utc` to `date -u` to get it to build (which should also work on linux)
> Construct BUILD_DATE using date -u for OSX support

- src/spec.cr
I know this is a small change but I noticed that Shards currently throws an ugly internal exception if the install command is run from a directory that is missing a `shard.yml` file.
Current Output:
```
Error opening file '.../bin/shard.yml' with mode 'r': No such file or directory (Errno)
*Errno::new<String>:Errno +426 [4416834874]
*File::new<String, String>:File +1217 [4416884113]
*File::read<String>:String +29 [4416882253]
~fun_literal_18 +2056 [4416880680]
__crystal_main +12189 [4416828125]
main +44 [4416835036]
```
This patch simply raises an error if the spec file is unable to be located in the current directory. The output of the error is much more user-friendly (in my opinion):
```
Error: Could not locate shard.yml
```
> Raise exception if unable to find spec file.

- src/package.cr
- src/resolvers/resolver.cr
- src/script.cr
- src/spec.cr
Dependencies may now have a post install script hook that will be
run whenever the dependency is installed or updated:
- scripts:
- postinstall: "cd ext && make"
refs #15
> Run postinstall script after installing dependency

- src/resolvers/resolver.cr
- src/spec.cr
It's probably a good idea to log any executed commands so that the user can verify commands.
This pull request simply logs the command as such:
```
Postinstall cd ext && make
```
This patch also fixes a small issue when run without a spec file. Previously the word `Error` was displayed twice (I submitted a PR for this earlier, but the error logging behaviour has changed since then).
> log commands that are executed

- src/resolvers/git.cr
- test/git_resolver_test.cr
By default, Crystal, prior to version 0.8.0, used to generate
an empty `Projectfile` with no listed dependencies:
```crystal
deps do
end
```
Developers might have committed this empty Projectfile to their
repositories, which then was parsed as legacy and attempt to build
the dependencies.
This result in an empty array of dependencies, which was incorrectly
concatenated to the fake spec built by Shards in attempt to process
legacy repositories. This was not proper YAML and thus, blow up
at runtime.
The fix provided here avoids that by resetting the empty list of
dependencies and simply return nothing, generating a proper YAML
and allowing the parsing to continue.
Fixes reported issue #42.
> Correctly parses empty Projectfile

- .travis.yml
- src/commands/check.cr
- src/resolvers/git.cr
The global `column.ui` option affects the listings of tags and
branches. This patch fixes this by adding `--column=never` to Git
commands when the installed Git supports the argument.
refs #35
> Fix: Git >= 1.7.11 may always list in columns

- src/cli.cr
- src/dependency.cr
- src/errors.cr
- src/lock.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
- src/spec.cr
- test/integration/install_test.cr
- test/integration/update_test.cr
- test/manager_test.cr
- test/path_resolver_test.cr
- test/spec_test.cr
- test/support/mock_resolver.cr
Specs are now parsed using the experimental `yaml_mapping` from Crystal 0.8.0. This avoids intermediary memory representations by instanciating objects and to enforce the expected format while parsing the YAML file.
The `yaml_mapping` may be dropped in favor to YAML::PullParser to return useful error messages to the user (with arrows pointing to source errors, etc).
refs #41
> Spec now uses yaml_mapping (experimental)

- README.md
The link at the top of the README pointed at `https://crystal-lang.org` but the site isn't available on port 443 so it was timing out.
> Fix a link

- README.md
The typo was giving me this error: `ld: warning: directory not found for option '-L/usr/local/lib/lib'`
> Removes 'lib/lib' typo that results incorrect path

- README.md
As a newbie to Crystal I tried to use the usage example from shards' README to get started.
It seems that `minitest`'s latest version is `0.3.1` and not `1.0.0` as stated in the README.
This commit fixes this issue.
> Use existing version of minitest in usage example

- SPEC.md
Changed "It should be intended with 2 spaces." to "It should be indented with 2 spaces."
> Fix spelling mistake in SPEC.md

- src/config.cr
Default supplied to `ENV.fetch` was always evaluated, even when the environment variable looked up was found, thus causing the computed information to be discarded.
Adjust so the default values are only computed when no environment information is found for these cases.
Thank you.
:heart: :heart: :heart:
> Delay evaluation of defaut values from ENV

- src/templates/shard.yml.ecr
For now, manastech/webmock has renamed to manastech/webmock.cr, we should upgrade the template. Details to see: https://github.com/manastech/webmock.cr
> upgrade shard template for manastech/webmock

- .gitignore
- SPEC.md
- src/config.cr
- src/logger.cr
- src/man/shards.1
- src/resolvers/git.cr
- src/resolvers/path.cr
- test/git_resolver_test.cr
- test/integration/install_test.cr
- test/integration/prune_test.cr
- test/integration_helper.cr
- test/path_resolver_test.cr
- test/test_helper.cr
- Shards counterpart to support https://github.com/crystal-lang/crystal/pull/2788
- closes #123 
- unblocks #126 
Breaking changes:
- dependencies are installed into the `lib` folder;
- dependencies are fully installed (not merely the `src`);
- `postinstall` scripts are now run from the root of a dependency, not the `src` folder.
> New Crystal search path algorithm

- src/cli.cr
- src/commands/version.cr
- test/integration/version_test.cr
Sometimes is useful to obtain the current version string of the library/project you're working on, either to help you determine if was bumped (when preparing for a new release) or when integrating it within the library's `VERSION` constant (through macros).
This change introduces `version` command for such purpose, allowing you retrieve from current directory (by default) or be able to provide a different path.
Usage example
```crystal
module Foo
VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}
end
```
Resulting in a `Foo::VERSION` matching the `version` defined in `shard.yml`.
Fixes #147
> Introduces `version` command to retrieve shards current version

- src/logger.cr
`severity` is now a Logger::Severity, not a string.
> Fix logger formatter for Crystal 0.23

- src/helpers/natural_sort.cr
I'm not sure about this, but I think this was an error. Take for example the commit hash in issue #162:
"341678090110cdb5436f75cc796c785ed392c4be"
Before this change, this natural sort implementation would first consider "341678090110" then skip the subsequent "c" then continue with "db5436f75cc796c785ed392c4be". This is because the `ia` and `ib` indexes get moved `size + 1` instead of just `size`. I made the correction and tests still pass. 
Apologies if I'm missing something about how the algo is supposed to work :).
> Corrects off by 1 error when applying natural sort between version descriptors.

- src/commands/install.cr
- src/commands/update.cr
- src/package.cr
- src/resolvers/git.cr
- test/git_resolver_test.cr
Specifying a Git refs (tag, branch or commit) used to inject that ref into the available versions array for the shard. This behavior caused an issue in NaturalSort when trying to resolve a version number to install.
The behavior was changed so the Git refs is no longer injected, but will be reported as the actual "version" to be installed.
Also introduces a `Package#report_version` method which returns a string describing which version (number) of a shard is installed, along with the Git refs which is installed. For example:
Installing dotenv (0.1.0 at master)
fixes #162
> Fix: installing Git refs

- SPEC.md
- src/commands/install.cr
- src/commands/update.cr
- src/package.cr
- src/resolvers/resolver.cr
- src/spec.cr
- test/integration/install_test.cr
- test/integration/update_test.cr
- test/integration_helper.cr
- test/spec_test.cr
- test/support/factories.cr
WIP to implement #95 as per https://github.com/crystal-lang/shards/issues/95#issuecomment-222552996
blocked by ~~#123~~ and maybe #124
> Install executables

- src/commands/build.cr
Hi @ysbaddaden !
Currently if I execute `shards build -v --stats --progress` I can't see the expected output:
```
shards build --stats --progress -v
Dependencies are satisfied
Building: scry
crystal build -o /home/main/Projects/scry/bin/scry src/scry.cr --stats --progress
``` 
With this PR I can get the full output:
```
shards build -v --stats --progress
Dependencies are satisfied
Building: scry
crystal build -o /home/main/Projects/scry/bin/scry src/scry.cr --stats --progress
Parse:                             00:00:00.000286771 (   0.25MB)
Semantic (top level):              00:00:00.410225224 (  52.33MB)
Semantic (new):                    00:00:00.002928317 (  52.33MB)
Semantic (type declarations):      00:00:00.036812337 (  60.33MB)
Semantic (abstract def check):     00:00:00.002699638 …
```
> Print output to STDOUT

- src/file_utils.cr
- src/resolvers/path.cr
- test/path_resolver_test.cr
Fixes #208
@ysbaddaden I was almost going crazy because `cleanup_install_directory` didn't remove symlinks to non-existing targets. It took my while to finally figure that `FileUtils.rm_rf` doesn't actually call the stdlib method but is a custom implementation which completely ignores broken symlinks.
I'd strongly suggest to rename that method (or the entire module) to a different name in order to avoid such mistakes.
> Fix path resolver recognize incorrect install path

- src/resolvers/git.cr
- test/integration/update_test.cr
Creating bare Git repositories doesn't configure the local repository to fetch remote refs, such as branches and tags, which totally broke the update command.
This patch reverts back to mirroring Git repositories, and verifies whether a cloned repository is valid, or not before fetching new refs.
fixes #211
> Fix: Git resolver doesnt pull tags anymore

- CHANGELOG.md
- Makefile
>  Fix: `install -t` isn't supported on macOS 

- .circleci/config.yml
Fixes #177.
Adds CircleCI as an alternative CI using docker images. 
* It will use crystal:latest image on every push, and
* It will build master using crystal:nightly image every midnight
* There is not much dependencies in shards, but I've already ~~shamelessly copy~~ setup the appropriate commands for caching the global shards cache between builds.
> Add CircleCI 2.0 with nightly builds

- src/commands/install.cr
- src/manager.cr
- test/integration/install_test.cr
If the dependency is a branch refs and we previously locked the dependency, we must declare that locked commit (for the install command only) otherwise we end up resolving the spec from the latest branch commit that may have changed dependencies, while still eventually installing the locked commit.
This situation is fixed with a hack in Manager to add the locked commit before the branch dependency is added, so the locked commit will have precedence over the branch.
fixes #219
> Fix: always resolve dependency spec at locked commit

- test/support/factories.cr
In the case of the user running the tests setting the git configuration commit.gpgSign=true, running the specs can prompt for a smartcard to be inserted or for the keychain to be unlocked. This is undesirable.
> Force git commits created by the spec suite not to be signed

- src/version.cr
When shards is used as a library, the former code would read VERSION file from main project folder (while shards typically sits in `lib/shard`). It would also complain if there is no VERSION file at the specified location.
The shell command can be replaced by `read_file` after the next Crystal release (or the one after that).
The git command in the next line will obviously fail as well, but it's not trivial to fix. It doesn't break building.
An optimal solution for using `shards` as a library would probably be that `shards version` command provides the commit hash of the installed version. This doesn't work when shards is built as an application because it would depend on a compiled version of itself.
> Fix macro command reference path relative to source location

- src/package.cr
- src/resolvers/git.cr
- test/git_resolver_test.cr
- test/support/factories.cr
Shards recognizes tags without 'v' prefix as valid version identifiers but then can't use them as valid ref for accessing it in the git repo. That leads to errors.
Maintainers of shards need to prefix release version tags with a `v`. This can be fixed retroactively.
A useful shell command for adding v-prefixed tags:
```bash
for tag in $(git tag --list | grep -P '^[\d.]+$'); do git tag v$tag $tag; done
```
This issue has been discussed in #108
> Enforce prefix 'v' in git version tags

- src/cli.cr
- src/commands/outdated.cr
- src/package.cr
- src/versions.cr
- test/integration/outdated_test.cr
Basically: it resolves dependencies just like the `install` command does, then reports any dependency that has a new release matching all constraints (`available: x.y.z`), and the latest release if it's different.
Optionally supports checking for pre-releases with `--pre`.
The command assumes that dependencies are installed. It doesn't fail if `shard.yml` is missing; maybe it should?
The command is meant for developers to know about new releases of dependencies, and thus always succeeds (i.e. `exit 0`) unless there was an error.
closes #56
> Add outdated command to know which dependencies are outdated

- src/commands/install.cr
- src/commands/update.cr
- src/package.cr
- test/integration/install_test.cr
- test/integration/update_test.cr
- test/integration_helper.cr
Postpones the execution of the postinstall script, so it's run after all dependencies have been installed, to solve the availability of transitive dependencies. Also postpones the installation of executables, since they're likely to be built by the postinstall script.
Links the project's `lib` folder as the shard's own `lib` folder, to solve the accessibility of transitive dependencies (for executable for the postinstall script). This solution was preferred over manipulating the CRYSTAL_PATH environment variable, since a wrapper script of the crystal executable could replace it (e.g. the `bin/script` of crystal's repository does just that).
closes #124
> Fix: transitive dependencies in postinstall script

- src/commands/install.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/update.cr
- src/package.cr
- src/solver/graph.cr
- test/integration/build_test.cr
- test/integration/install_test.cr
- test/integration/update_test.cr
- test/integration_helper.cr
- test/support/factories.cr
- 2fb303e now resolves HEAD to `x.x.x+git.commit.<sha1>` when a shard doesn't have any version tags;
- 42a7bf9 `Package` now resolves a SPEC at commit if present instead of the version tag; this caused bug #269 when a shard doesn't have version tags (`shard.yml` not found at version, despite `shard.yml` existing at commit).
~~I don't have time to write proper tests. If someone wants to take a stab at 'em!~~
closes #269
> Fix: Git default HEAD refs

- src/resolvers/git.cr
- test/git_resolver_test.cr
GitResolver#available_versions must no longer filter versions based on the Git refs of the initial dependency that created it. It must always report all versions, which are filtered later by the solver.
> Fix: GitResolver must report all available versions

- src/commands/prune.cr
- test/integration/prune_test.cr
The issue was found in the nightly builds.
> Fix: prune command must only remove directories

- src/solver.cr
- test/integration/install_test.cr
GitResolver#available_versions must no longer filter versions based on the Git refs of the initial dependency that created it. It must always report all versions, which are filtered later by the solver.
fixes #273
> Fix: Git refs must enable pre-release selection

- src/version.cr
- test/integration/build_test.cr
> Use read_file macro instead using OS-dependent `cat`

- SPEC.md
Fixes #251 
This adds properties `repository`, `homepage` and `documentation` to `SPEC.yml`.
I don't think there is any need to implement support in the shards executable for now.
> Add SPEC for repository, homepage, documentation properties

- src/solver/sat.cr
Fixes the SAT solver so it doesn't fill the memory. Doesn't fix the solver from being very long (not necessarily SAT being but the afterwards decision on the best outcome).
Refs #282
> Use Set instead of Array for memorizing conflicts

- src/version.cr
By default the shards binary embeds a build date which makes it
impossible to rebuild due to time differences. Use SOURCE_DATE_EPOCH to
use a predictable timestamp as input for the date function which in turn
makes shards reproducible.
Motiviation: https://reproducible-builds.org
> Make shards reproducible

- Makefile
Currently the Makefile makes use of the `**` wildcard. But that actually doesn't have any effect. I replaced that with `find` calls, that I hope are fully portable 🤞
> Replace glob patterns in Makefile with `find` command

- src/resolvers/resolver.cr
- src/script.cr
- test/integration/install_test.cr
When running `$ shards install` it will now append the shard name where the script is defined
For example when running it in lucky it will show the precompiled_tasks for avram and make bin from ameba are run.
```
... stripped ...
Installing teeplate (0.8.0)
Installing blank (0.1.0)
Installing db (0.8.0)
Installing pg (0.20.0)
Postinstall script/precompile_tasks (avram)
Postinstall make bin (ameba)
Writing shard.lock
```
When the command fails, [only the command is displayed](https://github.com/crystal-lang/shards/blob/0cda1578a12f6d59254b81c2b7a2386f34a3ea44/src/script.cr#L10) with no path/dependency name.
> Show the shard's name when running scripts

- shard.lock
- test/integration/install_test.cr
Upgrade the version of `molinillo` that fixes an error when trying to raise errors about circular dependencies.
> Fix detection of circular dependencies

- test/integration/prune_test.cr
This improves the coverage of the prune specs added when #57 was closed.
The hidden files are not removed because the `Dir[File.join(Shards.install_path, "*")]` will not enumerate it by default. With this PR we are stressing the check that existing files (not directories) in the `./lib` folders are kept. And not because they are hidden.
> Specs: check non hidden files are not pruned

- .circleci/config.yml
- .travis.yml
Plus some cleanup in circle ci config
Travis ran in 11min + queue
Circle ran in 7min + queue
Installing from homebrew even with caching takes a lot of time. But the main reason is to avoid hangs due while waiting for travis to give an osx instance.
> Move osx ci from Travis to Circle

- spec/unit/spec_helper.cr
- src/cli.cr
- src/commands/build.cr
- src/commands/check.cr
- src/commands/command.cr
- src/commands/init.cr
- src/commands/install.cr
- src/commands/list.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/prune.cr
- src/commands/update.cr
- src/config.cr
- src/logger.cr
- src/package.cr
- src/resolvers/git.cr
- src/resolvers/resolver.cr
I migrate shards code to use Log module API.
But allow compilation for logger module behind compare_versions.
Once we drop support for older Crystal that can be removed.
With the log module we could even be able to allow logging from molinillo solver be tweaking `CRYSTAL_LOG_SOURCES`. How cool is that 😍
> Use Crystal 0.34 Log module (if possible)

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/support/factories.cr
- src/molinillo_solver.cr
Currently a shard that was renamed in some point in history cannot be installed unless a version is specified. This is annoying, because for example this `shard.yml` fails with a misleading error:
```yml
name: test
version: 0.1.0
dependencies:
lucky:
github: luckyframework/lucky
```
```
$ shards install
Resolving dependencies
Fetching https://github.com/luckyframework/lucky.git
Error shard name (lucky_web) doesn't match dependency name (lucky)
```
This PR allows installing latest version of a shard (when no version is specified) or a previous version only if the name matches.
> Support shard renames

- spec/integration/install_spec.cr
- src/molinillo_solver.cr
I found this bug that confuses the Molinillo solver and it ends ignoring the lock in some situations like when adding a new dependency that have sub-dependencies already locked.
> Respect locks when adding new dependencies

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- src/commands/install.cr
- src/molinillo_solver.cr
This PR changes the way the content of `shards.lock` is used during dependency resolution. Instead of passing all o them blindly to the solver, they are traversed as a tree, starting from the dependencies specified explicitly in `shards.yml`, only if the version still matches, and following each sub-dependency recursively.
This fixes some issues:
* If the version in `shards.yml` is changed, running `shards` just does the update of that shard. 
* Running `shards update foo`, if `foo` has dependency `bar`, now it's not needed to run `shards update foo bar` to unlock `bar` (unless `bar` is also in `shards.yml`)
The behavior of `shards` is now more similar to `bundler`, and I think it's a good thing. Much more intuitive and simple to use.
> Automatic unlock on install and update

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- src/commands/install.cr
This is what @RX14 said on a previous PR (https://github.com/crystal-lang/shards/pull/337#issuecomment-605658181)
The logic was indeed wrong and I fixed it and added another test. I changed the order of the tests in the `validate` method because the solver adds a `version` on every lock, even for those with a `commit` [here](https://github.com/crystal-lang/shards/blob/fac08bce2c3482b10437eb8241bfa9565270ec0d/src/molinillo_solver.cr#L25).
Also, because the validation functions are now used only in production mode, the logic is simplified and they check only for exact match, version or commit.
> Fix validation in production mode for dependencies referenced by commit

- shard.lock
- shard.yml
I just released the first version (0.1.0) of the molinillo shard. Getting ready for the next release of Shards.
> Version bump (0.10.0) and update reference to molinillo shard

- .gitignore
- spec/integration/install_spec.cr
- spec/integration/prune_spec.cr
- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- spec/support/cli.cr
- spec/support/factories.cr
- spec/unit/git_resolver_spec.cr
- spec/unit/path_resolver_spec.cr
- src/commands/install.cr
- src/commands/outdated.cr
- src/commands/prune.cr
- src/dependency.cr
- src/lock.cr
- src/molinillo_solver.cr
- src/package.cr
- src/resolvers/git.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
- src/spec.cr
This ended up being a not so small PR and I have more changes coming, but I prefer to split here now that at least the tests are passing 😅 
This is mostly a refactor, although I fixed some cases of locks with commits that were either not working or working not totally on purpose.
For the user, there are two (non breaking) visible changes:
* There is a `shard_name.version` file for each shard within the `lib` directory. This replaces the `.sha1` file that was generated for shards not coming from a release version.
* The `shard.lock` file now contains `version` for both releases and git refs. For versions it's the same a before, but for git refs the version is stores something like: `0.9.0+git.commit.ed686ad3015f48f8b22cf4fbec80e8c8088ef44b`
Internally there are some refactors:
* Versions …
> Versioning rework

- spec/integration/init_spec.cr
- spec/integration/spec_helper.cr
- spec/support/cli.cr
- spec/support/requirement.cr
- spec/unit/dependency_spec.cr
- spec/unit/git_resolver_spec.cr
- spec/unit/lock_spec.cr
- spec/unit/path_resolver_spec.cr
- spec/unit/resolver_spec.cr
- spec/unit/spec_helper.cr
- spec/unit/spec_spec.cr
- spec/unit/versions_spec.cr
- src/commands/check.cr
- src/commands/install.cr
- src/commands/list.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/config.cr
- src/dependency.cr
- src/lock.cr
- src/molinillo_solver.cr
- src/package.cr
- src/requirement.cr
- src/resolvers/git.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
- src/spec.cr
- src/versions.cr
This is a refactor of dependency requirements (specifications of which versions are suitable for each dependency).
Currently, each dependency has different fields (`version`, `branch`, `tag`, `commit`) that declares the requirement. But this model is imprecise (allows invalid states), difficult to reason in code (`version` is sometimes a pattern, others an exact version) and requires constant parsing of the `version` field (for example to differentiate patterns, or exact version).
With this change, each `Dependency` now has only three fields: `name`, `resolver` and `requirement`. Also note that the relationship between `Dependency` and `Resolver` is now inverted. (In a future refactor I also plan to remove the `name` from `Resolver` making it totally independent from the dependency that …
> Rework of dependency and requirements

- src/dependency.cr
This is now unused and broken code after #354
> Remove obosolete Dependency#to_human_requirement

- spec/integration/install_spec.cr
- spec/unit/dependency_spec.cr
- spec/unit/lock_spec.cr
- src/dependency.cr
- src/requirement.cr
- src/resolvers/git.cr
Since #354, the reporting of conflicts didn't look nice. Now it looks back again like this:
```
$ shards install
Resolving dependencies
Unable to satisfy the following requirements:
- `db (0.2.0)` required by `shard.yml`
- `db (~> 0.1.0)` required by `mysql 0.1.0`
Failed to resolve dependencies
```
> Format dependency and requirements

- spec/integration/check_spec.cr
To avoid regressions in the future, make sure `check` passes even when there is a version mismatch with `shard.yml`.
Closes #353
> Add spec for check when there is a version mismatch

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/unit/spec_spec.cr
- src/molinillo_solver.cr
- src/resolvers/git.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
- src/spec.cr
Versions without a spec will just be considered as if they don't have dependencies, but a warning will be printed if a shard is installed without a shard.yml.
For example, `stefanwille/crystal-redis` didn't have a `shard.yml` in the first versions. But it will now install without problems if latest versions are used:
```
$ shards install
Resolving dependencies
Installing redis (1.11.0)
Writing shard.lock
```
However, when a version without spec is selected it will print the warning:
```
$ shards install
Resolving dependencies
Shard "redis" version (1.0.1) doesn't have a shard.yml file
Installing redis (1.0.1)
Writing shard.lock
```
Fixes #346
> Fix crash when a shard version didn't contain a shard.yml

- man/shards.1
- src/cli.cr
The `[<options>]` in the `build` argument was a bit misleading, it's more clear now on what options to use with `build`
> Explicitly state build_options in help output, fixes #363

- spec/integration/install_spec.cr
- spec/integration/prune_spec.cr
- spec/integration/spec_helper.cr
- spec/unit/info_spec.cr
- src/config.cr
- src/dependency.cr
- src/info.cr
- src/requirement.cr
- src/resolvers/git.cr
- src/resolvers/resolver.cr
Since #349 every installed shard is accompanied by a `.version` file with the real installed version. This clutters the `lib` directory. This PR replaces all those files with a single `lib/.shards.info` file. This file is also a YAML so the contents could be extended in the future with any required metadata.
> Replace .version files with a single .shards.info

- spec/integration/install_spec.cr
- src/commands/install.cr
Since #354 unchanged locks are undetected and always overwritten after the "install" command
> Fix: shard.lock is always overwritten even when dependencies are up to date

- src/logger.cr
This might be seen as a silly thing but it could be actually pretty annoying sometimes. I know some terminals have settings to ensure minimal contrast but I think it's better not to rely on that configuration.
Because we cannot aim for any background color, I just tested with the extremes: black and white. For each case, here is how it looks before and after the change. Bright colors look great on dark background, but I can barely see WARN on the light background. BTW, `bundler` uses the same colors.
> Use less bright colors for output

- src/dependency.cr
- src/lock.cr
- src/molinillo_solver.cr
- src/package.cr
- src/resolvers/resolver.cr
There was a require loop `resolvers/resolver > spec > config > info > lock > package > resolvers/*` which would cause code like the following to fail:
```Cr
require "./src/resolvers/git"
require "./src/resolvers/path"
```
```
In src/resolvers/path.cr:4:24
4 | class PathResolver < Resolver
^-------
Error: undefined constant Resolver
```
Lock doesn't depend on Package, so there's no need to require it there.
> Remove unnecessary require to break loop

- shard.yml
- src/config.cr
- src/logger.cr
- src/package.cr
- src/resolvers/path.cr
This makes Crystal 0.34 the minimal version to compile Shards.
> Add compatibility with Crystal 0.35. Drop compatibility with < 0.34

- spec/integration/install_spec.cr
- spec/integration/prune_spec.cr
- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- spec/support/cli.cr
- spec/support/factories.cr
- src/commands/command.cr
- src/config.cr
- src/package.cr
This version will display a warning when the `lib` directory is found but not the `crystal_shards`.
Closes #258
> Change install dir to `.crystal/shards`

- Makefile
This is to avoid the situation where, if the `shard.lock` has a mtime more recent than `lib` directory, the dependencies are installed every time. Is there a better solution for this?
> Makefile: touch lib directory after installing dependencies

- SPEC.md
- spec/unit/spec_spec.cr
- src/spec.cr
> Add error on duplicate arguments in shard.yml

- spec/support/factories.cr
this prevents errors if users running specs have set up gpg signing in
their git config
> make sure tags aren't signed

- spec/integration/install_spec.cr
- spec/unit/git_resolver_spec.cr
- src/resolvers/git.cr
Based on the work done by @straight-shoota in #386 
I will submit the changes to show the full hash on errors on a different PR.
Fixes: #384
> Fix: allow commit hashes to be abbreviated

- spec/integration/install_spec.cr
- spec/support/cli.cr
- src/commands/command.cr
- src/config.cr
This reverts #367 for now. Please look at https://github.com/crystal-lang/crystal/pull/9280#issuecomment-629501668 for the reasons behind this new decision.
> Revert change of install dir

- spec/integration/install_spec.cr
- spec/unit/git_resolver_spec.cr
- src/resolvers/git.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
Currently when a git ref doesn't exist, the resolver just returns an empty array for the available versions. This makes the solver to fail with a confusing message. For example:
```
Unable to satisfy the following requirements:
- `db (branch foo)` required by `shard.yml`
```
With this PR, the error is handled more prematurely, thus providing better info:
```
Could not find branch foo in the repository https://github.com/crystal-lang/crystal-db.git for shard "db"
```
Also, if a commit hash is used, the full hash is displayed:
```
Could not find commit fd686ad3015f48f8b22cf4fbec80e8c8088ef44b in the repository https://github.com/crystal-lang/crystal-db.git for shard "db"
```
Related to #384, #386
> Make errors with git refs more descriptive

- SPEC.md
- spec/integration/install_spec.cr
- spec/unit/version_req_spec.cr
- spec/unit/versions_spec.cr
- src/dependency.cr
- src/requirement.cr
- src/versions.cr
This adds support for version specifiers like: `>= 1.0.0, < 2.0`
I need this to implement #365, but I think it's also nice addition. Other dependency managers also support expressions like that.
> Support intersection of versions

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/support/factories.cr
- spec/unit/git_resolver_spec.cr
- src/cli.cr
- src/commands/install.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/update.cr
- src/config.cr
- src/molinillo_solver.cr
- src/resolvers/crystal.cr
This PR implements what's discussed in #365 
I had to also make the assumption that when the `crystal` property is not present, the expression `< 1.0.0` is assumed. This is because old shards in the past didn't specify the `crystal` version. If we don't make this assumption, once Crystal 1.0.0 is released, old shard versions will be installed by default. This has the implication that the parameter is now mandatory after `1.0.0` but I think that's a good thing and according to what was discussed.
> Use `crystal` property to filter shard compatibility

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/support/cli.cr
- spec/unit/lock_spec.cr
- src/commands/check.cr
- src/commands/command.cr
- src/commands/install.cr
- src/commands/lock.cr
- src/commands/prune.cr
- src/commands/update.cr
- src/info.cr
- src/lock.cr
This upgrades the `version` in `shards.lock` to `2.0`, because it effectively cannot be used by previous versions (git refs are stored as part of the version metadata).
> Bump lock version

- spec/integration/install_spec.cr
- src/info.cr
Files `.sha1` left from previous Shards version are now deleted when the `.shards.info` is generated the first time.
> Delete old .sha1 files

- Makefile
Similar to https://github.com/crystal-lang/crystal/pull/9471
Follow-up to https://github.com/crystal-lang/distribution-scripts/pull/71#discussion_r442992993
I'm only adding release, debug, static to use the same in crystal repo. But I think having FLAGS is enough.
> Add convenient makefile arguments for packaging

- src/resolvers/git.cr
Resolves #316
Git repository requests over HTTP can result in 401 Authentication Required status code. This is typically the case when a repository is private. Some git providers also return this status code when a repository exists to avoid disclosing the existence of private repositories.
By default, `git clone` prompts for credentials when it receives a 401 status code. When `shards install` uses `git clone`, this leads to unexpected and misleading behaviour. `shards install` is not meant to be used interactively, so this prompt should be completely disabled.
This PR implements this by using the environment variable `GIT_ASKPASS` set to a value resulting in false. It can still be overriden by setting the environment variable.
> Disable interactive credential prompt for git resolver

- spec/support/factories.cr
Just a tiny change that makes debugging failing specs easier.
> Spec: Add stdout and stderr to FailedCommand message

- spec/integration/install_spec.cr
* 1900/01/01 is not a representable date on 32-bit Linux and restricted to the oldest date which is representable.
See crystal-lang/crystal#9542 for more info.
> Fix spec for running under 32-bit Linux

- spec/integration/install_spec.cr
- src/cli.cr
This allows users to set `--no-color` globally
And is another way to use `--ignore-crystal-version` most likely in CI
Idea mentioned in https://github.com/crystal-lang/shards/issues/413#issuecomment-647768257
> Allow shards to read SHARDS_OPTS for addition command options

- src/cli.cr
- src/config.cr
Follow up of #417.
Add --ignore-crystal-version as OptionParser option so the 
shards --ignore-crystal-version 
or
SHARDS_OPTS=--ignore-crystal-version shards
do not pick --ignore-crystal-version as the command name in args[0]?
> Allow SHARDS_OPTS/--ignore-crystal-version in build & default command

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- spec/support/factories.cr
- src/commands/install.cr
- src/molinillo_solver.cr
- src/resolvers/git.cr
- src/resolvers/resolver.cr
Changing the source from git to path in the shard.yml, in the precense of a shard.lock file didn't trigger an update of the lockfile. The `outdated_lockfile?` logic didn't consider all the information that will be used to generate that file (resolver key and source were missing).
Now lock constraints are not added if the resolver from the shard.yml and from the shard.lock differ.
It will now handle better ambiguous sources for the same name. Before this PR one was used because the cache was accessed by name only. Now it depends on name, key and (normalized) source.
The resolver cache needed to be reset in some helper methods on integration specs to avoid misleading results. Well, now that the cache key depends not only in the name that change is not _really needed_, but I think is better …
> Handle ambiguous dependencies and update shard.lock on if source of dependency changes change

- src/commands/command.cr
Each command implements a different run. There is no generic Command reference that requires a unified API among all the subclasses.
Required change due to https://github.com/crystal-lang/crystal/pull/9585
> Remove abstract def run definition

- .circleci/config.yml
Grab version from lock and install using curl
This will fix shards nightly builds. ~~This is the analogous to https://github.com/crystal-lang/distribution-scripts/pull/71~~ , curl is not available in crystal docker image. This PR uses --ignore-crystal-version
> Fix nightly builds

- .circleci/config.yml
- shard.lock
- shard.yml
- spec/support/factories.cr
- src/errors.cr
- src/logger.cr
- src/requirement.cr
Code cleanups plus followup for #421 😞
> Bump required crystal to 0.35

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- src/package.cr
Currently running an `install` after changing the resolver from `path` to `git` doesn't do anything because `GitResolver` fails to detect that the current install is not what's required.
Now the `Package` uses the `.shards.info` to check that the resolver and version matches to figure out if the dependency is installed.
> Fix: reinstall when resolver changes

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- spec/support/cli.cr
- spec/unit/override_spec.cr
- src/commands/command.cr
- src/commands/install.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/update.cr
- src/config.cr
- src/dependency.cr
- src/lock.cr
- src/molinillo_solver.cr
- src/override.cr
- src/package.cr
- src/resolvers/git.cr
- src/resolvers/resolver.cr
Implements most of #412 .
Reads a `shard.override.yml` (or the file specified by `SHARDS_OVERRIDE`) to override the source and restriction of a dependency. There are no changes regarding CLI options of shards.
This allows the cases described in the motivation of #412
* Use local working copies
* Use a shard version despite published constraints
* Fixing a dependency
* Checking app against development version of a dependency
---
On a project that uses `github:crystal-lang/crystal-sqlite3` it will current use `crysta-db 0.8.0`.
```yaml
name: sample
version: 0.1.0
dependencies:
sqlite3:
github: crystal-lang/crystal-sqlite3
version: ~> 0.15.0
crystal: 0.35.1
```
```yaml
version: 2.0
shards:
db:
git: https://github.com/crystal-lang/crystal-db.git
version: 0.8.0
sqlite3:
git: …
```
> Shards overrides

- spec/integration/list_spec.cr
- spec/unit/git_resolver_spec.cr
- spec/unit/package_spec.cr
- spec/unit/path_resolver_spec.cr
- spec/unit/resolver_spec.cr
- spec/unit/spec_helper.cr
- src/commands/check.cr
- src/commands/list.cr
- src/commands/outdated.cr
- src/info.cr
- src/package.cr
- src/resolvers/crystal.cr
- src/resolvers/git.cr
- src/resolvers/path.cr
- src/resolvers/resolver.cr
This is the first part of a refactor I'm working on to better separate responsibilities between internal entities in Shards. I split these changes in two so it can be reviewed more easily. With this PR the `Resolver` still represents a source to obtain different versions of a shard, but the installation is delegated completely to the `Package` class.
This will make more sense with the second part, where locks and installed packages (`Shards.info.installed`) will return instances of `Package` instead of `Dependency`. In other words, finally the `Dependency` will represent just the intention with some more or less precise definition of which version is desired, while a `Package` represents a specific version that must be or is already installed.
There is a small change in behaviour after …
> Move install responsibilities from Resolver to Package

- spec/integration/spec_helper.cr
- spec/unit/info_spec.cr
- spec/unit/lock_spec.cr
- src/commands/check.cr
- src/commands/install.cr
- src/commands/list.cr
- src/commands/outdated.cr
- src/dependency.cr
- src/info.cr
- src/lock.cr
- src/molinillo_solver.cr
- src/package.cr
- src/resolvers/git.cr
This is the followup from #426. Previously, locks and installed shards were represented as `Dependency` with a `Version` requirement. But that forces to do castings and checks on many places. With this change the code is simplified, and the check for invalid dependency is only done while parsing.
> Use Package for locks and installed shards

- spec/integration/check_spec.cr
- spec/integration/list_spec.cr
- spec/integration/outdated_spec.cr
- src/commands/check.cr
- src/commands/outdated.cr
~~Based on #428~~
Some minor fixes to deal with source changes and overrides on the listed commands.
> Update check, list, outdated commands to work against source changes and overrides

- Makefile
- src/version.cr
This closely follows https://github.com/crystal-lang/crystal/pull/9088 and moves non-essential shell commands to Makefile, passing the values through environment variables.
This is part of work to bring 'shards' to Windows.
> Don't use compile-time shell commands to determine build timestamp

- src/commands/prune.cr
- src/helpers/path.cr
- src/package.cr
- src/resolvers/git.cr
This is part of work to bring 'shards' to Windows.
> Use Process.quote instead of the old platform-specific helper

- spec/support/factories.cr
- src/resolvers/git.cr
- src/script.cr
This is part of work to bring 'shards' to Windows.
> Don't use POSIX-specific shell constructs

- src/resolvers/git.cr
to avoid relying on a shell to pipe into `tar`.
Caveat: `git checkout` also updates the index in the repository, but that shouldn't be a problem here (is there even any index in a bare repo to start with?)
This is part of work to bring 'shards' to Windows.
> Use git's `checkout` feature directly to write out repo files

- src/cli.cr
This allows additional functionality to be added to the shards command in a similar way extra commands are added to `git`. Basically, if the shards command isn't found in shards itself, it will run `shards-#{command}`, passing STDIO through. If there is no executable that matches the attempted command, the regular shards usage message is shown.
> Add a fallback to alternate shards commands

- src/resolvers/git.cr
Occasionally, though it's always happen with my connection, either `git clone --mirror` or `git fetch --all` via http will tend to fail with closed connection.
Doing retry directly on the git command seem to fix the situation. In addition, bundle also doing this with their [git_proxy](https://github.com/rubygems/rubygems/blob/f7f8f7c968e31ebcadf1cc7b8243ef023920a65f/bundler/lib/bundler/source/git/git_proxy.rb#L157-L161)
> Improve git reliability by retrying on failures

- spec/unit/spec_spec.cr
- src/ext/yaml.cr
- src/spec.cr
This patch allows empty scalars as values for mappings or sequences in `shard.yml`.
So this is considered a valid specification:
```yaml
name: foo
version: 0.1.0
dependencies:
```
Previously, this caused a YAML parser error: `Expected MAPPING_START but was SCALAR at line 3, column 15`
There's no change to internal behaviour because empty mappings and sequences were already allowed (`dependencies: {}`).
So this is just a simple UX feature that avoids errors when for example all dependencies are removed but the `dependencies:` key isn't.
Both empty string and YAML null value (`~`) are accepted.
> Spec: Allow empty scalar for mappings/sequences

- spec/integration/install_spec.cr
- spec/integration/update_spec.cr
- spec/unit/lock_spec.cr
- src/commands/install.cr
- src/commands/update.cr
- src/lock.cr
With this change `shards update` and `shards install` (except with `--production` option) *always* write `shard.lock` (or touch if there are not changes) even if there are no dependencies.
Resolves #445
Unlocks #444
> Write lockfile even when there are no dependencies

- spec/integration/outdated_spec.cr
- src/commands/outdated.cr
`shards outdated` would break with `Empty enumerable` error if a dependency does not have any releases. This patch fixes that.
> Fix command outdated for dep with no releases

- README.md
`CRFLAGS` was dropped in favour of generic `CRYSTAL_OPTS` in #344
/cf https://github.com/crystal-lang/shards/pull/414#issuecomment-758347018
Maybe we should add a `release=1` flag to the makefile for this use case to add some abstraction?
> Fix README referencing CRFLAGS

- SPEC.md
Currently linked anchor does not exist on upstream site.
> Fix broken link to git url types

- Makefile
- spec/integration/install_spec.cr
- spec/integration/update_spec.cr
- src/commands/install.cr
- src/commands/update.cr
- src/resolvers/git.cr
This patch makes sure that modification times are always in order `lib > shard.lock > shard.yml`. This is necessary for mtime-based dependency resolution for example with make.
Resolves #390
> Touch install_path and lockfile to express dependency

- spec/integration/outdated_spec.cr
- spec/integration/spec_helper.cr
- src/commands/outdated.cr
This fixes `shards outdated` to work correctly with non-release versions. Currently it reports every version as outdated which is not the latest release, even if the installed commit is ahead of the latest release.
Resolves #446
In the example from #446, it's pretty obvious: The installed version is head on `master`, so it's really the latest and should not be listed as outdated.
When the requirement is a branch, the intention is to track that path. So the highest available version is head of that branch.
If there is a tagged releases with a higher version number (independent of the requirement restriction), that should always be treated as latest.
Commit and tag requirements are complicated because they provide no context to depict intention. A typical use case would be to pin an …
> Fix outdated command with non-release installed

- src/resolvers/git.cr
The method does not work anymore because there is not variable or
method `dependency`.
> Remove dysfunctional `GitResolver#matches?`

- src/resolvers/git.cr
The working directory passed to `run` should be the parameter `path`,
not `local_path`.
> Fix working directory in `capture`

- spec/integration/spec_helper.cr
- spec/unit/git_resolver_spec.cr
- src/resolvers/git.cr
> feat: treat github sources as case insensitive

- spec/integration/install_spec.cr
- src/molinillo_solver.cr
- src/resolvers/resolver.cr
When running `shards install` and the locked version is not available in the source, it's an error. This error is now more explicit in describing this situation and recommends to run `shards update`.
This patch does not change any behaviour (as proposed in https://github.com/crystal-lang/shards/issues/465#issuecomment-763253847), it just improves the error reporting.
Related to #465
> Improve error message when locked version is missing in source

- docs/shards.adoc
- man/shards.1
- spec/integration/install_spec.cr
- spec/integration/list_spec.cr
- src/cli.cr
- src/commands/check.cr
- src/commands/install.cr
- src/commands/list.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/update.cr
- src/config.cr
This patch adds flags `--frozen` and `--without-development` which allow to use the two functions of `--production` individually.
There's also a behavioural change included in ff457ff which lets `--frozen` fail when `shard.lock` is missing. This should actually be the expected behaviour, also for `--production`.
Resolves most of #452
> Add `--frozen` and `--without-development` CLI flags

- docs/shards.adoc
- man/shard.yml.5
- man/shards.1
- spec/integration/install_spec.cr
- spec/integration/update_spec.cr
- src/cli.cr
- src/config.cr
- src/package.cr
Partially implements the suggestions of https://github.com/crystal-lang/shards/issues/468#issuecomment-767064550
The postinstall instructions will be logged with a trailing `(skipped)`.
Usually the postinstall will generate target binaries that are then linked/copied by `Package#install_executables`.
With this PR the target binaries will not exist and wont be linked/copied, which is fine.
To complete the idea https://github.com/crystal-lang/shards/issues/468#issuecomment-767064550 and decouple the commands for Windows environments in a comfortable way I am not sure if it's better to a) make the `shards postinstall --dry-run [shard names]` perform postinstall and install_executables or if b) postinstall and install-executables should be different commands. 
Either way that can be handled …
> Add --skip-postinstall cli option to install and update

- .github/workflows/ci.yml
Refactored some parts as well like `include`-ing windows in the `matrix` instead of having it there from start - especially apt as windows support is still in-the-works.
> Add macOS nightlies to CI

- spec/integration/install_spec.cr
- spec/integration/update_spec.cr
- src/commands/command.cr
- src/commands/install.cr
- src/commands/update.cr
Fix-up for #444. There's an unconditional `touch` on `./lib`. But that folder might not exist when no dependencies are installed. This ends up creating a file at this path, which is obviously not ideal because later you might want to install dependencies and shards expects a directory.
This patch makes sure to always create the folder.
Ref. https://github.com/crystal-lang/shards/pull/477#issuecomment-783651180
The newly added spec for `shard.lock` modification time was not broken, but added it for coverage.
> Fix touch install_path to not accidentally create file

- docs.mk
The call is totally broken and doesn't actually work (would need to define the function using `define`). It just happend to still succeed inside a git repository.
I don't think we really need file-specific SOURCE_DATE_EPOCH, so we can spare the call entirely and just use a global variable.
This change also allows to specify `SOURCE_DATE_EPOCH` as an external variable when building docs.
Ref https://github.com/crystal-lang/shards/issues/253#issuecomment-785079152
> Fix broken SOURCE_DATE_EPOCH in docs.mk

- spec/integration/build_spec.cr
- src/commands/build.cr
If no `targets` are defined in `shard.yml`, the command `shards build` should fail with an error message instead of silently succeeding without actually building anything.
/cc https://forum.crystal-lang.org/t/trouble-with-building-shard/3122
> Let `shards build` error if no targets defined

- docs/shard.yml.adoc
- spec/integration/spec_helper.cr
- src/molinillo_solver.cr
Fixes #413
As I said in https://github.com/crystal-lang/shards/issues/413#issuecomment-727671407, when discussing this breaking check, there was no motivation specified in terms of how this makes developers' lives better at all. And seems that the majority does not want this check.
Behavior before #395:
`crystal: ` field does nothing
Behavior now:
`crystal` unspecified means `< 1.0.0`
`crystal: x.y.z` means `>= x.y.z, <(x+1).0`
Behavior with this PR:
`crystal` unspecified means `*` / does mostly nothing
`crystal: x.y.z` means `>= x.y.z`
It is still possible to explicitly write `crystal: ">=0.35, <2.0"` and the check *will* trigger.
> Don't default the Crystal version to "<1.0.0", use only the lower bound

- spec/support/factories.cr
> stop expecting master to be the default branch for git

- docs/shard.yml.adoc
- docs/shards.adoc
- man/shard.yml.5
- man/shards.1
- spec/integration/install_spec.cr
- spec/integration/update_spec.cr
- src/cli.cr
- src/config.cr
- src/package.cr
This patch adds a `--skip-executables` flag for the `install` and `update` commands which disables installing files defined as `executables` in any `shard.yml`
This is a minimal solution for #498 with behaviour I think we can all agree on.
I would go one step further and also imply this flag when `--skip-postinstall` is used, because executables are typically built by postinstall hooks and if they're not executed, installing the executables will fail (see https://github.com/crystal-lang/shards/issues/498#issuecomment-826122183).
But this is not strictly necessary for this PR, we can at least provide an option (even if it's more lengthy) to skip installation of executables.
The manpages diff is big and contains unrelated changes because of #505, which is included as the first commit here …
> Add `--skip-executables`

- Makefile
The `shard.lock` recipe fails if `SHARDS=false` (i.e. building from scratch without a previously installed `shards` binary), we must skip `$SHARDS update` in that case.
see https://github.com/crystal-lang/crystal/issues/10861
> [Makefile] Fix shard.lock recipe

- src/commands/build.cr
- src/logger.cr
> Fix pass no-color and verbose flags to crystal build

- docs/shard.yml.adoc
- man/shard.yml.5
- spec/unit/versions_spec.cr
- src/versions.cr
> Add `!=` operator for version resolve

- spec/integration/build_spec.cr
After crystal-lang/crystal#11473 the following spec in shards' spec suite is broken:
```
1) build reports error when target failed to compile
Failure/Error: ex.stdout.should contain("unexpected token: ...")
Expected:   "I: Dependencies are satisfied\nI: Building: app\nE: Error target app failed to compile:\n\e[33mUsing compiled compiler at /home/johannes/Projects/crystal-lang/crystal/.build/crystal\e[0m\nIn src/cli.cr:1:8\n\n 1 | a = ......\n            ^\nError: unexpected token: \"...\"\n\n"
to include: "unexpected token: ..."
```
> Fix unexpected token compiler error match

- spec/integration/spec_helper.cr
- spec/integration/update_spec.cr
- spec/support/factories.cr
- src/commands/build.cr
- src/config.cr
This is a reissue of #415 reduced to the original scope. It makes `shards` honour the `CRYSTAL` environment variable when calling the `crystal` program to determine the Crystal version and for `shards build`.
Resolves #406
> Honour `CRYSTAL` env var

- spec/support/factories.cr
Some Git-related tests required external configuration of email and name. This forced tweaks in CI and other environments to have those set globally before running tests.
This change makes this self-contained: Git repositories created part of the test suite are going to automatically set a default email and name.
Note: this might look silly, but removes the need to set that up when running the specs in a controlled container environment (and not a development one) and has no impact on existing CI or others running it.
Thank you.
❤️ ❤️ ❤️
> No longer depend of external git user config

- .circleci/config.yml
circleci is deprecating the images with xcode 11.1, so we need to update.
I'm updating to the latest version available, 13.2.1
https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
> [CI] Update circleci xcode 13.2.1

- spec/integration/build_spec.cr
- spec/support/factories.cr
- src/commands/build.cr
Solves #535 by outputting the STDERR of the `crystal` build to the STDERR of the `shards` process _only if the build is successful_. This allows to notice deprecation warnings and the like.
In order to test it, I had to concatenate the STDOUT and STDERR, which isn't as clean as possible but works.
> Feat: output STDERR from the building process

- spec/integration/install_spec.cr
- spec/integration/spec_helper.cr
- src/resolvers/path.cr
This patch enhances the error information when a path resolver can't find `shard.yml`: It shows the expanded path of the directory where it looked for the file.
/cc #308,  #309
> Add expanded local path to `shard.yml` error message in `PathResolver`

- src/resolvers/git.cr
I have couple of hooks in my global git template (skeleton) directory, this breaks shards completely and it was such a pain to figure it out. Symptoms are:
```
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Installing pg (0.24.0)
Failed git --work-tree=/home/lzap/work/invidious/lib/pg checkout
refs/tags/v0.24.0 -- . ().
Maybe a commit, branch or file doesn't exist?
```
The patch overrides the user-defined configuration so git checkouts are clean.
> Avoid user defined git template in resolver

- spec/integration/install_spec.cr
- src/resolvers/path.cr
Resolves #308
[as per suggestion](https://github.com/crystal-lang/shards/issues/308#issuecomment-569764134) of @ysbaddaden 
⚠️ WARNING: I just did what was suggested. It seems to compile, but I did not actually unit test this because _most_ of the unit tests fail for me without any changes on my part.
> re-enabled ~ support in path resolver

- spec/integration/build_spec.cr
- spec/support/factories.cr
Clear environment when running integration spec. If the environment has `CRYSTAL_OPTS=--error-on-warnings` it would get passed through to the compiler and the spec fails (see https://github.com/crystal-lang/test-ecosystem/runs/6116920991).
This is a minimal change to fix the immediate issue. It could be considered that we apply this to more uses of `run`. Maybe inheriting the environment should even be opt-in.
> Fix clear ENV in integration spec

- src/resolvers/resolver.cr
All implementations of `#install_sources` have a second parameter called `install_path`, only the abstract definition in `Resolver` uses the name `install_dir`, which results in a warning:
> positional parameter 'install_path' corresponds to parameter 'install_dir' of the overridden method Shards::Resolver#install_sources(version : Version, install_dir : String), which has a different name and may affect named argument passing
This patch renames the parameter name in the abstract definition to match the one used in all the implementations.
> Adjust parameter name for `Resolver#install_sources`

- src/resolvers/fossil.cr
This is something I ran into while actually using the new Fossil resolver heavily.  If you have multiple shards coming from the same website (say, chiselapp.com), the resolver would sometimes fail because it would think a shard was pulled when it wasn't.  This fixes the problem.
> Fix Fossil resolver when multiple dependencies are coming from the same website

- spec/integration/prune_spec.cr
- src/commands/prune.cr
I noticed that if you run `shards prune` in a project with the following two conditions:
1. `shards.lock` exists
2. The install directory (`lib/`) does not exist
Then the command raises an exception. This might not be a super common scenario, but in the context of CI it can be frustrating for this command to throw and then interrupt the whole job rather than just not doing anything.
> prune - Don't raise an exception if install_path doesn't exist

- spec/integration/run_spec.cr
- spec/support/factories.cr
- src/commands/run.cr
When running `shards run`, you should be able to work with standard input.
Fix #550
> Inherit the standard input descriptor

- src/cli.cr
This patch adds a helpful message when encountering a failure to create symlinks in Windows which can likely be fixed by enabling developer mode.
The implementation is very dumb, just catching all `File::AccessDeniedError` and check whether it was caused by a missing privilege for `symlink` creation.
Alterantively, we could use a wrapper for `File.symlink` which checks this directly at every call site (it's only 2). But I think it's easier this way.
Resolves #556
> Improve error message when symlink failed on Windows

- src/resolvers/git.cr
- src/resolvers/hg.cr
When a git command failed and the error output did not start with "error:", the entire message would be hidden.
With this change, it's printed in full.
The other resolvers already have a similar behaviour in place. I'm also adjusting the on for hg in the second commit to follow git.
This was reported in https://forum.crystal-lang.org/t/shards-install-ends-with-faild-git-tag-list-column-never/5242
> Fix avoid swallowing error message if git command failed

- spec/support/cli.cr
- src/commands/command.cr
- src/ext/yaml.cr
- src/resolvers/fossil.cr
- src/resolvers/git.cr
- src/resolvers/hg.cr
- src/versions.cr
Applies formatter update from https://github.com/crystal-lang/crystal/pull/12951
> `crystal tool format` with 1.8-dev

- spec/integration/install_spec.cr
- src/resolvers/git.cr
The equivalent method in the other resolvers already prints the original error message, just `git` didn't do that.
Fixes #525
> Fix swallowing original error message in `git_retry`

- docs/shards.adoc
The previous documentation was prone to misunderstanding (example: #584). This makes it more clear what the flag is about.
> Clarify documentation of `--local` flag

- Makefile
- spec/unit/fossil_resolver_spec.cr
- spec/unit/git_resolver_spec.cr
- spec/unit/hg_resolver_spec.cr
Allow skipping specs for individual resolvers which can be useful when the respective dependency (the resolver binary) is unavailable in the spec environment.
> Add tags to resolver specs

- .github/workflows/ci.yml
- man/shard.yml.5
- man/shards.1
Manpages in `man/` are generated from adoc files in `docs/`. Both source and target format are checked into git.
Often it's forgotten to update the manpages when the adoc sources are updated (latest example: #587).
This change ensures that the manpages are up to date in CI by rebuilding them and checking if they produce a diff.
> ci: Ensure manpages are generated with no diff

- src/package.cr
> Do not try to override existing lib path in dependency

- src/config.cr
Similar to crystal-lang/crystal#11436, this allows Shards to attempt the following cache directories on Windows:
* `%LOCALAPPDATA%\shards\cache`
* `%USERPROFILE%\.cache\shards`
* `%USERPROFILE%\.shards`
> Support more cache directories on Windows

- .gitignore
Includes the debug information file too.
> Add Windows binary paths to `.gitignore`

- .github/workflows/ci.yml
- Makefile.win
The docs-related targets are dropped, because manfiles do not make sense on Windows. Everything else should work, in particular setting up the Git commit hash and the build date for `bin\shards.exe --version`. Setting `%SHARDS%` to `false` also works as long as both `curl` and `tar` are available ([Windows 10 should come with them already](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)).
> Add `Makefile.win`

- spec/integration/prune_spec.cr
This is needed for one spec to pass on Windows where `rm` doesn't exist as a built-in.
> Use `FileUtils.rm_rf` instead of shell command in spec

- src/cli.cr
- src/commands/command.cr
- src/commands/install.cr
- src/commands/lock.cr
- src/commands/outdated.cr
- src/commands/update.cr
- src/helpers.cr
Explicitly detects the presence of Developer mode or the ability to enable `SeCreateSymbolicLinkPrivilege`, and errors immediately upon running any command that potentially fetches dependencies (`build`, `install`, `lock`, `outdated`, `run`, `update`). This reduces the chances of leaving the `lib` directory in an incomplete state in the middle of those commands.
The old exception handler for symlink failures is now gone; if an unhandled exception shows up, that means this PR is not exhaustive enough.
> Detect symlink creation capability on Windows

- docs/shard.yml.schema.json
Implements #622. I can add automated tests if desired. After this, I can add it to [JSON Schema Store](https://github.com/SchemaStore/schemastore).
I wasn't sure if we should restrict additional properties in the file, as there may be other tools that add stuff to the shard.yml. Off the top of my head, I can't remember any though, and they should probably move those kinds of things to their own config file.
Also if you're using VSCode, you can add this to the `.vscode/settings.json` and it will use the schema to vaidate the shard.yml that shards uses. I used this for testing.
```jsonc
// .vscode/settings.json
{
"yaml.schemas": {
"docs/shard.yml.schema.json": "shard.yml"
}
}
```
> Add JSON schema for `shard.yml`

- .envrc
- .gitignore
- .pre-commit-config.yaml
- README.md
- devenv.lock
- devenv.nix
- devenv.yaml
Configuration for a https://devenv.sh environment with all necessary tools to build and test shards.
I'm using this locally and it makes sense to share it in the repo so others can make use of it as well.
> Add devenv configuration

- src/resolvers/git.cr
I don't think there's a good reason to read the config file directly. Going through the CLI is easier and safer.
ref: https://github.com/crystal-lang/shards/pull/638#issuecomment-2328312139
> Run `git config` instead of reading `config` file manually

- .github/workflows/ci.yml
Installing mercurial via pip on Windows fails due to a missing dependency. But the chocolatey package works, so let's use that.
Actually, let's use OS-specific package managers on all platforms to install mercurial (like we already do for fossil).
The spec suite still fails due to https://github.com/crystal-lang/shards/pull/639#issuecomment-2358259257, but that's a different issue (#639). This patch makes it even work at all.
Resolves #640
> Install mercurial via OS package manager

- src/resolvers/git.cr
Fixup for https://github.com/crystal-lang/shards/pull/639
`git config` exits with status code 1 if the config value was not found. This would raise an exception but instead, `#valid_repository?` should just return `false`. This patch fixes that. It also moves from `--get-regexp` to plain `--get`. The remote name `origin` is fixed anyway (e.g. `git ls-remote --get-url origin` in `#origin_url`) and we only care about this.
The change is broken on Windows. This was masked by the CI failure due to https://github.com/crystal-lang/shards/issues/640.
Closes #642
> Fix `GitResolver#valid_repository?`

- Makefile
Like crystal-lang/crystal#15123, but for Shards.
As with other platforms, an initial build can be done by pointing `CRYSTAL` to the MinGW-w64 build artifact and setting `SHARDS=false`.
> Support `.exe` file extension in `Makefile` on MSYS2

- .github/workflows/ci.yml
- .github/workflows/docs.yml
The docs workflow only needs to run when there are changes to the docs or doc processing.
> [CI] Run docs check in separate workflow with path restriction

- docs/shard.yml.adoc
- docs/shard.yml.schema.json
- man/shard.yml.5
- spec/unit/git_resolver_spec.cr
- src/resolvers/git.cr
Enhances the `shard.yml` configuration to support [Codeberg](https://codeberg.org/),
a popular Git hosting service in Germany, as a dependency source.
This allows developers to specify Codeberg repositories directly in their configuration.
Example usage:
```yaml
dependencies:
foo:
codeberg: repo/foo
```
> Add support for Codeberg as a git resolver

- docs/shard.yml.adoc
- docs/shard.yml.schema.json
- man/shard.yml.5
- man/shards.1
- spec/unit/spec_spec.cr
- src/spec.cr
I'd love to see #221 implemented. This is my go at it!
> Use SPDX license identifiers for `license` in `shard.yml`

- spec/integration/help_spec.cr
- src/cli.cr
Restores the behavior where `--help` would always skip the command to be invoked, while still allowing to pass the `--help` to external subcommands:
The following commands print the help message and exit:
- `shards --help`
- `shards --local --help`
- `shards update --help`
While the following tries to call `shards-unknown --help` then falls back to print the help message and exit:
- `shards unknown --help` 
Relies on a fixed list of the builtin command names to avoid having each `when` case starting with `display_help_and_exit(opts) if display_help`.
closes #649
> Fix: --help option

- Makefile
Per convention, `DESTDIR` should only be expanded directly in the install/uninstall targets, not prefixed into the directory variables.
Ref https://github.com/crystal-lang/crystal/pull/15444
> Expand `DESTDIR` outside of prefixed dir variables

- spec/unit/dependency_definition_spec.cr
- src/dependency_definition.cr
- src/resolvers/resolver.cr
This proposes an alternative implementation for #673
> URI-based dependency parsing
